version: "3.1"

services:
  integration-tests:
    build:
      context: .
      dockerfile: ./integration-tests/Dockerfile
    hostname: integration-tests
    depends_on:
      - cart
      - loms
    environment:
      CART_GRPC_ADDR: "cart:50051"
      CART_GATEWAY_ADDR: "cart:8080"
      LOMS_GRPC_ADDR: "loms:50052"
      LOMS_GATEWAY_ADDR: "loms:8081"
    command: ["go", "test", "-v", "./..."]
